"""Foundations for the offline BB-Agent decision kernel."""

from bb_agent.evaluator import (
    CONFIG_VERSION as EVALUATION_CONFIG_VERSION,
)
from bb_agent.evaluator import (
    DEFAULT_EVALUATION_PROFILE,
    DEFAULT_UNIT_VALUE_POLICY,
    CandidateEvaluation,
    DecisionEvaluation,
    DecisionSelection,
    EpistemicRankingScenario,
    EvaluationProfile,
    EvaluationScales,
    EvaluationWeights,
    UnitValuePolicy,
    evaluate_decision,
    score_candidate_features,
    select_candidate_evaluations,
)
from bb_agent.evaluator import (
    MODEL_VERSION as EVALUATOR_MODEL_VERSION,
)
from bb_agent.features import (
    MODEL_VERSION as TACTICAL_FEATURE_MODEL_VERSION,
)
from bb_agent.features import (
    EpistemicAssignment,
    EpistemicFeatureScenario,
    MetricRange,
    OutcomeModelFacts,
    TacticalFeatures,
    extract_candidate_feature_scenarios,
    extract_candidate_features,
)
from bb_agent.fixtures import (
    FixtureEnvelope,
    FixtureMetadata,
    ReplayInput,
    load_fixture,
    save_fixture,
    validate_fixture_pair,
)
from bb_agent.live_canonical import (
    live_battle_id,
    live_source_generation,
    materialize_live_tactical_state,
)
from bb_agent.live_ingest import (
    LIVE_CAPTURE_VERSION,
    LIVE_ENVELOPE_VERSION,
    AcceptedLiveDecision,
    LiveCompatibility,
    LiveIngestEvent,
    LiveIngestMachine,
    LiveIngestStatus,
    LiveKernelIdentity,
    LiveLogTailer,
    LiveRecord,
    LiveRecordType,
    current_live_kernel_identity,
    decode_live_frame,
    encode_live_frame,
)
from bb_agent.outcomes import AttackOutcome, OutcomeBranch, evaluate_ordinary_attack
from bb_agent.tactical_state import TacticalState
from bb_agent.trace import (
    TRACE_VERSION,
    ComponentDelta,
    DecisionTrace,
    RankDelta,
    TraceDiff,
    TraceReplayResult,
    compare_traces,
    replay_decision_trace,
    run_decision_trace,
)
from bb_agent.validation import (
    EXPECTATION_VERSION,
    HARNESS_VERSION,
    ActionFactExpectation,
    AssertionStatus,
    CorpusCoverageSummary,
    CorpusValidationReport,
    ExplanationExpectation,
    FixtureExpectations,
    FixtureValidationReport,
    MetricRef,
    NearTieExpectation,
    NumericRelation,
    RegressionKind,
    RegressionReport,
    RelationOperator,
    TopKExpectation,
    ValidationAssertion,
    classify_trace_change,
    run_fixture_validation,
    run_validation_corpus,
)
from bb_agent.versions import CURRENT_VERSIONS, ContractVersions

__all__ = [
    "CURRENT_VERSIONS",
    "EXPECTATION_VERSION",
    "HARNESS_VERSION",
    "LIVE_CAPTURE_VERSION",
    "LIVE_ENVELOPE_VERSION",
    "AcceptedLiveDecision",
    "LiveCompatibility",
    "LiveIngestEvent",
    "LiveIngestMachine",
    "LiveIngestStatus",
    "LiveKernelIdentity",
    "LiveLogTailer",
    "LiveRecord",
    "LiveRecordType",
    "current_live_kernel_identity",
    "decode_live_frame",
    "encode_live_frame",
    "live_battle_id",
    "live_source_generation",
    "materialize_live_tactical_state",
    "TRACE_VERSION",
    "ActionFactExpectation",
    "AssertionStatus",
    "ContractVersions",
    "CorpusCoverageSummary",
    "CorpusValidationReport",
    "ExplanationExpectation",
    "FixtureEnvelope",
    "FixtureExpectations",
    "FixtureMetadata",
    "FixtureValidationReport",
    "MetricRef",
    "NearTieExpectation",
    "NumericRelation",
    "RegressionKind",
    "RegressionReport",
    "RelationOperator",
    "ReplayInput",
    "TacticalState",
    "TopKExpectation",
    "ValidationAssertion",
    "AttackOutcome",
    "CandidateEvaluation",
    "ComponentDelta",
    "DEFAULT_EVALUATION_PROFILE",
    "DEFAULT_UNIT_VALUE_POLICY",
    "DecisionEvaluation",
    "DecisionSelection",
    "DecisionTrace",
    "EpistemicRankingScenario",
    "EVALUATION_CONFIG_VERSION",
    "EVALUATOR_MODEL_VERSION",
    "EpistemicAssignment",
    "EpistemicFeatureScenario",
    "EvaluationProfile",
    "EvaluationScales",
    "EvaluationWeights",
    "MetricRange",
    "OutcomeBranch",
    "OutcomeModelFacts",
    "RankDelta",
    "TACTICAL_FEATURE_MODEL_VERSION",
    "TacticalFeatures",
    "TraceDiff",
    "TraceReplayResult",
    "UnitValuePolicy",
    "classify_trace_change",
    "compare_traces",
    "evaluate_decision",
    "evaluate_ordinary_attack",
    "extract_candidate_feature_scenarios",
    "extract_candidate_features",
    "load_fixture",
    "replay_decision_trace",
    "run_decision_trace",
    "run_fixture_validation",
    "run_validation_corpus",
    "save_fixture",
    "score_candidate_features",
    "select_candidate_evaluations",
    "validate_fixture_pair",
]
