from pathlib import Path

validation_path = Path("src/bb_agent/validation.py")
validation = validation_path.read_text()
anchor = '''    if diff.added_action_ids or diff.removed_action_ids:\n        return RegressionReport(\n            RegressionKind.HARD_GATED_FAILURE,\n            diff,\n            "same-fixture legal candidate set changed without a ruleset/input change",\n        )\n\n    engine_changed = _engine_model_identity(before) != _engine_model_identity(after)\n'''
replacement = '''    if diff.added_action_ids or diff.removed_action_ids:\n        return RegressionReport(\n            RegressionKind.HARD_GATED_FAILURE,\n            diff,\n            "same-fixture legal candidate set changed without a ruleset/input change",\n        )\n\n    before_status = str(before.generation.get("decision_status") or "")\n    after_status = str(after.generation.get("decision_status") or "")\n    expected_status = None if expectations is None else expectations.expected_status\n    if after_status != "SUCCESS" and after_status != expected_status:\n        return RegressionReport(\n            RegressionKind.HARD_GATED_FAILURE,\n            diff,\n            (\n                "unexpected decision failure/coverage status introduced: "\n                f"{before_status!r} -> {after_status!r}"\n            ),\n        )\n\n    missing_evaluations = tuple(\n        sorted(set(_candidate_records(before)) - set(_candidate_records(after)))\n    )\n    if after_status == "SUCCESS" and missing_evaluations:\n        return RegressionReport(\n            RegressionKind.HARD_GATED_FAILURE,\n            diff,\n            "successful decision stopped evaluating legal candidates: "\n            + ", ".join(missing_evaluations),\n        )\n\n    engine_changed = _engine_model_identity(before) != _engine_model_identity(after)\n'''
if validation.count(anchor) != 1:
    raise SystemExit("validation classifier anchor count != 1")
validation = validation.replace(anchor, replacement)
validation_path.write_text(validation)

test_path = Path("tests/test_validation.py")
tests = test_path.read_text()
helper_anchor = '''def _rebuild_trace(\n    trace,\n    *,\n    engine=None,\n    generation=None,\n    evaluations=None,\n    selection=_UNSET,\n):\n    selection_value = trace.selection if selection is _UNSET else selection\n    return DecisionTrace.create(\n        input=dict(trace.input),\n        engine=dict(trace.engine if engine is None else engine),\n        generation=dict(trace.generation if generation is None else generation),\n        evaluations=tuple(\n            dict(item)\n            for item in (trace.evaluations if evaluations is None else evaluations)\n        ),\n        selection=(None if selection_value is None else dict(selection_value)),\n        failure=None if trace.failure is None else dict(trace.failure),\n        performance=dict(trace.performance),\n    )\n'''
helper_replacement = '''def _rebuild_trace(\n    trace,\n    *,\n    engine=None,\n    generation=None,\n    evaluations=None,\n    selection=_UNSET,\n    failure=_UNSET,\n):\n    selection_value = trace.selection if selection is _UNSET else selection\n    failure_value = trace.failure if failure is _UNSET else failure\n    return DecisionTrace.create(\n        input=dict(trace.input),\n        engine=dict(trace.engine if engine is None else engine),\n        generation=dict(trace.generation if generation is None else generation),\n        evaluations=tuple(\n            dict(item)\n            for item in (trace.evaluations if evaluations is None else evaluations)\n        ),\n        selection=(None if selection_value is None else dict(selection_value)),\n        failure=None if failure_value is None else dict(failure_value),\n        performance=dict(trace.performance),\n    )\n'''
if tests.count(helper_anchor) != 1:
    raise SystemExit("test helper anchor count != 1")
tests = tests.replace(helper_anchor, helper_replacement)
insert_anchor = '''def test_corpus_summary_reports_taxonomy_severity_and_nonblocking_reviews():\n'''
new_test = '''def test_regression_classification_hard_fails_unexpected_coverage_loss():\n    authority = _authority()\n    state = _snapshot(authority, _wait(), _wait(ActionKind.END_TURN))\n    before = run_decision_trace(authority, state)\n    assert before.selection is not None\n\n    problem = {\n        "code": "EVALUATION_UNSUPPORTED",\n        "message": "synthetic newly unsupported evaluation",\n        "path": "action_affordances.actions[0]",\n        "mechanic_id": "test.new_coverage_gap",\n    }\n    generation = dict(before.generation)\n    generation["decision_status"] = "INCOMPLETE_COVERAGE"\n    generation["coverage_diagnostics"] = [problem]\n    after = _rebuild_trace(\n        before,\n        engine=_versioned_engine(before, ".coverage-gap"),\n        generation=generation,\n        evaluations=(),\n        selection=None,\n        failure={\n            "stage": "coverage",\n            "status": "INCOMPLETE_COVERAGE",\n            "problems": [problem],\n        },\n    )\n    assert before.generation["legal_candidates"] == after.generation["legal_candidates"]\n\n    calibration_fixture = _fixture(\n        state,\n        None,\n        fixture_id="unexpected-coverage-gap",\n        severity=FixtureSeverity.CALIBRATION,\n        review_status=ReviewStatus.DRAFT,\n    )\n    hard = classify_trace_change(calibration_fixture, before, after)\n    assert hard.kind is RegressionKind.HARD_GATED_FAILURE\n    assert hard.diff.added_action_ids == ()\n    assert hard.diff.removed_action_ids == ()\n    assert "INCOMPLETE_COVERAGE" in hard.message\n\n    expected_fixture = _fixture(\n        state,\n        {\n            "version": EXPECTATION_VERSION,\n            "expected_status": "INCOMPLETE_COVERAGE",\n            "allow_model_version_change": True,\n        },\n        fixture_id="expected-coverage-gap",\n        severity=FixtureSeverity.CALIBRATION,\n        review_status=ReviewStatus.REVIEWED,\n    )\n    expected = classify_trace_change(expected_fixture, before, after)\n    assert expected.kind is RegressionKind.INTENDED_MODEL_VERSION_CHANGE\n\n\n'''
if tests.count(insert_anchor) != 1:
    raise SystemExit("test insertion anchor count != 1")
tests = tests.replace(insert_anchor, new_test + insert_anchor)
test_path.write_text(tests)

doc_path = Path("docs/VALIDATION.md")
doc = doc_path.read_text()
doc_anchor = '''A version/config change is called intended only when the fixture explicitly sets `allow_model_version_change`. A recommendation swapping between two members of the fixture's `acceptable_top1` set is distinguished from a true gated failure. Trace/component deltas remain attached to the classification so #24–#26 reviews can explain why output changed.\n'''
doc_replacement = '''A version/config change is called intended only when the fixture explicitly sets `allow_model_version_change`. A recommendation swapping between two members of the fixture's `acceptable_top1` set is distinguished from a true gated failure. Trace/component deltas remain attached to the classification so #24–#26 reviews can explain why output changed.\n\nRegression classification is same-fixture and hard-regression checks have precedence over all versioned review categories. Legal candidate additions/removals, an unexpected non-`SUCCESS` decision/coverage status, loss of a legal candidate evaluation while the decision still claims `SUCCESS`, semantic output drift under identical engine/model/config identity, and unpermitted disappearance of modeled scoring/risk/uncertainty/explanation components are all `HARD_GATED_FAILURE`. A dedicated coverage fixture may classify an intended versioned failure only when it explicitly declares that resulting failure in `expected_status`.\n'''
if doc.count(doc_anchor) != 1:
    raise SystemExit("validation doc anchor count != 1")
doc = doc.replace(doc_anchor, doc_replacement)
doc_path.write_text(doc)
